### ISSUE TITLE
AWS CloudWatch reporter

### ISSUE THREAD

**Issue by cfbarbero** [alhardy/AppMetrics.Reporters#30]
What is necessary to create an AWS CloudWatch reporter.

**Comment by alhardy** [comment]
@cfbarbero you can have a look at the [InfluxDB Reporter](https://github.com/alhardy/AppMetrics.Extensions.InfluxDB) or [Elasticsearch Reporter](https://github.com/alhardy/AppMetrics.Extensions.Elasticsearch) as a guide. Should out if anything's not clear, created a new repo for this, [AppMetrics.Extensions.AWS](https://github.com/alhardy/AppMetrics.Extensions.AWS).

I'm also on AWS in my day job, been thinking about looking at [AWS XRay](https://aws.amazon.com/xray/) rather than CloudWatch.

**Comment by alhardy** [comment]
See https://github.com/alhardy/AppMetrics.Extensions.AWS
